services:
  app_1:
    build: ./2_backend
    container_name: nombre_app_1
    networks:
      - red_1
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=monolito
      - DB_USER=usuario
      - DB_PASSWORD=1234
    ports:
      - "3001:3000"

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=monolito
    networks:
      - red_1
    volumes:
      - datos_postgres:/var/lib/postgresql/data

networks:
  red_1:
    driver: bridge

volumes:
  datos_postgres:
    driver: local
