FROM node:22-alpine

COPY . .

RUN npm install

# Instalar postgres server

RUN  apk update && apk add postgresql postgresql-contrib
RUN mkdir /run/postgresql
RUN chown postgres:postgres /run/postgresql
USER postgres
RUN mkdir /var/lib/postgresql/data
RUN chmod 0700 /var/lib/postgresql/data
RUN initdb -D /var/lib/postgresql/data
RUN pg_ctl start -D /var/lib/postgresql/data && \
    psql --command "CREATE USER usuario WITH PASSWORD '1234';"&& \
    psql --command "CREATE DATABASE monolito OWNER usuario;" && \
    pg_ctl stop -D /var/lib/postgresql/data


EXPOSE 3000
CMD su-exec postgres pg_ctl -D /var/lib/postgresql/data && node init-db.js && tail -f /dev/null